name: text-workshop
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - jupyterlab
  - notebook
  - matplotlib
  - python=3.6
  - seaborn
  - scikit-learn
  - nltk
  - beautifulsoup4
  - gensim
  - spacy
  - wordcloud
  - tensorflow=1.12
  - tensorflow-hub=0.4.0
  - pip
  - pip:
    - contractions
    - tf-sentencepiece==0.1.81
    - sentencepiece
    - "https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.0.0/fr_core_news_sm-3.0.0.tar.gz#egg=fr_core_news_sm==3.0.0"
    - "https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.0.0/de_core_news_sm-3.0.0.tar.gz#egg=de_core_news_sm==3.0.0"